[tool.poetry]
name = "poetry-poems"
version = "0.1.0"
description = ""
authors = ["harper25 <olesjakubb@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
flake8 = "^3.8.3"
pytest-coverage = "^0.0"

[tool.poetry.scripts]
poems = "poetry_poems.cli:poems"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=. --cov-config=.coveragerc --cov-report term"
testpaths = [
    "tests"
]
